tournament:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: tournament
    username: root
    password: 4275
  redis:
    host: localhost
    port: 6379
    password: 4275
    database: 0  #不是必须的，默认0


