server:
  port: 8090

spring:
  application:
    name: tournament
  profiles:
    active: dev

  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${tournament.datasource.driver-class-name}
      url: jdbc:mysql://${tournament.datasource.host}:${tournament.datasource.port}/${tournament.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${tournament.datasource.username}
      password: ${tournament.datasource.password}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
