server:
  port: 8092

spring:
  application:
    name: tournament
  profiles:
    active: dev
  redis:
    host: ${tournament.redis.host}
    port: ${tournament.redis.port}
    password: ${tournament.redis.password}
    database: ${tournament.redis.database}  #不是必须的，默认0

  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${tournament.datasource.driver-class-name}
      url: jdbc:mysql://${tournament.datasource.host}:${tournament.datasource.port}/${tournament.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${tournament.datasource.username}
      password: ${tournament.datasource.password}

mybatis-plus:
  #mapper配置文件
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.ybk.entity # 替换为实体类所在包
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: IGNORED

ybk:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: admin
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: admin_token
    # 设置jwt签名加密时使用的秘钥
    leader-secret-key: leader
    # 设置jwt过期时间
    leader-ttl: 7200000
    # 设置前端传递过来的令牌名称
    leader-token-name: leader_token
    # 设置jwt签名加密时使用的秘钥
    referee-secret-key: referee
    # 设置jwt过期时间
    referee-ttl: 7200000
    # 设置前端传递过来的令牌名称
    referee-token-name: referee_token